import type { Metadata } from "next";
import { Roboto_Condensed, Roboto_Mono } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const robotoCondensedSans = Roboto_Condensed({
  variable: "--font-roboto-condensed",
  subsets: ["latin"],
});

const robotoCondensedSansMono = Roboto_Mono({
  variable: "--font-roboto-condensed-mono",
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${robotoCondensedSans.variable} ${robotoCondensedSansMono.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
